name: "laravel-app"
type: "php:7.4.28"
build:
   flavor: "composer"
relationships:
   database: "mysql:mysql"
hooks:
   build: |
      set -e
      cp .env.example .env
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
