"https://{default}/":
    type: upstream
    upstream: "app:http"
    passthru: "/index.php"

"http://{default}/":
    type: redirect
    to: "https://{default}/"

"POST /calculate":
    type: upstream
    upstream: "app:http"
    passthru: "/index.php"
    overrides:
        "http-basic": off